// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvnQyujG2s0-qarejkSvsI2jyWttHW2k',
    appId: '1:487131338835:web:5f3625462ac08bffeccea6',
    messagingSenderId: '487131338835',
    projectId: 'task-app-45006',
    authDomain: 'task-app-45006.firebaseapp.com',
    storageBucket: 'task-app-45006.appspot.com',
    measurementId: 'G-KY9EQQQZN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5E_G0ECiwIPsx5AqBTugmxMFf71sgBRU',
    appId: '1:487131338835:android:869e9b4d1545049deccea6',
    messagingSenderId: '487131338835',
    projectId: 'task-app-45006',
    storageBucket: 'task-app-45006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOcaqO3JFz6l6ABlgmglspnN3VKqo9cc',
    appId: '1:487131338835:ios:97912498774c4c7deccea6',
    messagingSenderId: '487131338835',
    projectId: 'task-app-45006',
    storageBucket: 'task-app-45006.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOcaqO3JFz6l6ABlgmglspnN3VKqo9cc',
    appId: '1:487131338835:ios:bfd01c5226e0a91aeccea6',
    messagingSenderId: '487131338835',
    projectId: 'task-app-45006',
    storageBucket: 'task-app-45006.appspot.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
